name: Build
on: [push]
jobs:
  Compile:
    runs-on: ubuntu-latest
    container: 
      image: emscripten/emsdk:2.0.7
      options: --workdir /github/workspace
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: ./build-web.sh
      - uses: actions/upload-artifact@v4
        with:
          name: Artifact
          path: dist/
       
